#!/usr/bin/env bash
# Deploy listeners and site to taurus (listen.home.arpa). Idempotent; run from
# anywhere in the repo. One-time host setup is described in deploy/README.md.
#
# Sources come from site/_config/sources.json: every entry gets a listener
# instance (listen-listener@<slug>) and nginx routes under /<slug>/.
set -euo pipefail
cd "$(dirname "$0")/.."

host="${DEPLOY_HOST:-taurus-mike}"
stage=/tmp/listen-deploy
cfg=site/_config/sources.json
gen=bin/deploy-gen

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }
[[ -f $cfg ]] || { echo "$cfg is missing (see sources.example.json)" >&2; exit 1; }

echo "checking $cfg"
jq -e '
  (.sources | length > 0)
  and ([.sources[].slug | test("^[a-z0-9][a-z0-9-]{0,62}$")] | all)
  and ([.sources[].slug] | length == (unique | length))
  and ([.sources[].listener.port] | length == (unique | length))
  and ([.sources[].listener.port | type == "number" and . > 1024 and . < 65536] | all)
  and ([.sources[] | .listener.input | type == "string" and (test("\\s") | not)] | all)
  and ([.sources[] | (.listener.args // [])[] | type == "string" and (test("\\s") | not)] | all)
' "$cfg" >/dev/null || { echo "$cfg: invalid (slugs, unique ports, inputs and args without spaces)" >&2; exit 1; }

echo "generating per-source files"
rm -rf "$gen" && mkdir -p "$gen/sources"
jq -c '.sources[]' "$cfg" | while read -r s; do
  slug=$(jq -r .slug <<<"$s")
  args=$(jq -r '["-addr", "127.0.0.1:\(.listener.port)", "-in", .listener.input] + (.listener.args // []) + (if .audio then ["-audio"] else [] end) | join(" ")' <<<"$s")
  printf '# Generated by scripts/deploy-taurus.sh from sources.json; do not edit.\nLISTEN_ARGS="%s"\n' "$args" > "$gen/sources/$slug.env"
done
{
  echo "# Generated by scripts/deploy-taurus.sh from sources.json; do not edit."
  jq -r '.sources[] | "
location ^~ /\(.slug)/ws/ {
    include snippets/proxy-params.conf;
    rewrite ^/\(.slug)(/ws/.*)$ $1 break;
    proxy_pass http://127.0.0.1:\(.listener.port);
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection \"upgrade\";
    proxy_buffering off;
    proxy_read_timeout 1h;
    proxy_send_timeout 1h;
}
location ^~ /\(.slug)/api/ {
    limit_except GET HEAD { deny all; }
    include snippets/proxy-params.conf;
    rewrite ^/\(.slug)(/api/.*)$ $1 break;
    proxy_pass http://127.0.0.1:\(.listener.port);
}"' "$cfg"
} > "$gen/listen-sources.conf"
slugs=$(jq -r '[.sources[].slug] | join(" ")' "$cfg")

echo "building listener (linux/amd64, static)"
(cd listener && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=vendor -trimpath -o ../bin/listen-listener-linux-amd64 ./cmd/listener)

ssh "$host" "rm -rf $stage && mkdir -p $stage/sources"
scp -q bin/listen-listener-linux-amd64 "deploy/systemd/listen-listener@.service" \
  deploy/nginx/listen.home.arpa.conf deploy/php-fpm/listen.conf "$gen/listen-sources.conf" "$host:$stage/"
scp -q "$gen"/sources/*.env "$host:$stage/sources/"

# Contact form: mail.php (gitignored) from .email (gitignored), with the
# rate-limit directory that exists on taurus.
scripts/mail-config.sh /var/lib/listen-web

echo "syncing site"
rsync -rlt --delete --exclude .DS_Store --exclude '*.example.*' \
  --rsync-path="sudo rsync" site/ "$host:/var/www/listen.home.arpa/"

echo "installing"
ssh "$host" "sudo bash -s" <<SH
set -euo pipefail
chown -R root:root /var/www/listen.home.arpa
find /var/www/listen.home.arpa -type d -exec chmod 0755 {} +
find /var/www/listen.home.arpa -type f -exec chmod 0644 {} +
# Credentials: readable by PHP only.
if [ -f /var/www/listen.home.arpa/_config/mail.php ]; then
  chown root:www-data /var/www/listen.home.arpa/_config/mail.php
  chmod 0640 /var/www/listen.home.arpa/_config/mail.php
fi
install -m 0755 $stage/listen-listener-linux-amd64 /usr/local/bin/listen-listener
install -m 0644 "$stage/listen-listener@.service" "/etc/systemd/system/listen-listener@.service"

# Migration from the single-source service.
if [ -f /etc/systemd/system/listen-listener.service ]; then
  systemctl disable --now --quiet listen-listener.service || true
  rm -f /etc/systemd/system/listen-listener.service /etc/default/listen-listener
fi

install -d -m 0755 /etc/listen/sources
install -d -o www-data -g www-data -m 0700 /var/lib/listen-web   # contact form rate limit
for f in /etc/listen/sources/*.env; do
  [ -e "\$f" ] || continue
  slug=\$(basename "\$f" .env)
  case " $slugs " in *" \$slug "*) ;; *)
    echo "removing source \$slug"
    systemctl disable --now --quiet "listen-listener@\$slug" || true
    rm -f "\$f" ;;
  esac
done
install -m 0644 $stage/sources/*.env /etc/listen/sources/
systemctl daemon-reload
for slug in $slugs; do
  systemctl enable --quiet "listen-listener@\$slug"
  systemctl restart "listen-listener@\$slug"
done

if ! cmp -s $stage/listen.conf /etc/php/8.3/fpm/pool.d/listen.conf; then
  install -m 0644 $stage/listen.conf /etc/php/8.3/fpm/pool.d/listen.conf
  php-fpm8.3 -t
  systemctl reload php8.3-fpm   # graceful; other pools keep serving
fi
install -m 0644 $stage/listen-sources.conf /etc/nginx/snippets/listen-sources.conf
install -m 0644 $stage/listen.home.arpa.conf /etc/nginx/sites-available/listen.home.arpa
ln -sf /etc/nginx/sites-available/listen.home.arpa /etc/nginx/sites-enabled/listen.home.arpa
nginx -t -q
systemctl reload nginx
rm -rf $stage
for slug in $slugs; do
  printf '%-22s %s\n' "\$slug" "\$(systemctl is-active listen-listener@\$slug)"
done
SH
echo "done: https://listen.home.arpa/"
