#!/usr/bin/env bash
# Generates the per-source deploy files from site/_config/sources.json:
#   <out>/sources/<slug>.env    LISTEN_ARGS for listen-listener@<slug>
#   <out>/listen-sources.conf   nginx routes /<slug>/ws/… and the three API paths the
#                               browser uses: api/state/current, api/motifs and
#                               api/history/events?type=narrative.update. The rest
#                               (motif details, feature history) stays on 127.0.0.1.
#   <out>/slugs                 the slugs, space separated
# Used by scripts/deploy-staging.sh and scripts/deploy-ionos.sh.
#   scripts/gen-sources.sh <out> [extra nginx directives for every route]
#
# Listening mode: NODE_MODE (continuous | on-demand, default continuous) and
# NODE_IDLE_AFTER (default 30s) are the node's defaults. A source can override
# them on every node with "listener": {"mode": …, "idle_after": …}.
set -euo pipefail
cd "$(dirname "$0")/.."

out="${1:?usage: gen-sources.sh <out> [nginx directives]}"
extra="${2:-}"
cfg=site/_config/sources.json
node_mode="${NODE_MODE:-continuous}"
node_idle="${NODE_IDLE_AFTER:-30s}"
case $node_mode in continuous|on-demand) ;; *) echo "NODE_MODE must be continuous or on-demand" >&2; exit 1 ;; esac

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }
[[ -f $cfg ]] || { echo "$cfg is missing" >&2; exit 1; }

jq -e '
  (.sources | length > 0)
  and ([.sources[].slug | test("^[a-z0-9][a-z0-9-]{0,62}$")] | all)
  and ([.sources[].slug] | length == (unique | length))
  and ([.sources[].listener.port] | length == (unique | length))
  and ([.sources[].listener.port | type == "number" and . > 1024 and . < 65536] | all)
  and ([.sources[] | .listener.input | type == "string" and (test("\\s") | not)] | all)
  and ([.sources[] | (.listener.args // [])[] | type == "string" and (test("\\s") | not)] | all)
  and ([.sources[] | .listener.mode // "continuous" | IN("continuous", "on-demand")] | all)
  and ([.sources[] | .listener.idle_after // "30s" | test("^[0-9]+(ms|s|m|h)$")] | all)
' "$cfg" >/dev/null || { echo "$cfg: invalid (slugs, unique ports, inputs and args without spaces, mode, idle_after)" >&2; exit 1; }

rm -rf "$out" && mkdir -p "$out/sources"
jq -c '.sources[]' "$cfg" | while read -r s; do
  slug=$(jq -r .slug <<<"$s")
  args=$(jq -r --arg mode "$node_mode" --arg idle "$node_idle" '
    ["-addr", "127.0.0.1:\(.listener.port)", "-in", .listener.input] + (.listener.args // [])
    + (if .audio then ["-audio"] else [] end)
    + (if (.listener.mode // $mode) == "on-demand" then ["-on-demand", "-idle-after", (.listener.idle_after // $idle)] else [] end)
    | join(" ")' <<<"$s")
  printf '# Generated by scripts/gen-sources.sh from sources.json; do not edit.\nLISTEN_ARGS="%s"\n' "$args" > "$out/sources/$slug.env"
done
{
  echo "# Generated by scripts/gen-sources.sh from sources.json; do not edit."
  jq -r --arg extra "$extra" '.sources[] | "
location ^~ /\(.slug)/ws/ {\($extra)
    include snippets/proxy-params.conf;
    rewrite ^/\(.slug)(/ws/.*)$ $1 break;
    proxy_pass http://127.0.0.1:\(.listener.port);
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection \"upgrade\";
    proxy_buffering off;
    proxy_read_timeout 1h;
    proxy_send_timeout 1h;
}
location = /\(.slug)/api/state/current {\($extra)
    limit_except GET HEAD { deny all; }
    include snippets/proxy-params.conf;
    rewrite ^/\(.slug)(/api/.*)$ $1 break;
    proxy_pass http://127.0.0.1:\(.listener.port);
}
location = /\(.slug)/api/motifs {\($extra)
    limit_except GET HEAD { deny all; }
    include snippets/proxy-params.conf;
    rewrite ^/\(.slug)(/api/.*)$ $1 break;
    proxy_pass http://127.0.0.1:\(.listener.port);
}
location = /\(.slug)/api/history/events {\($extra)
    limit_except GET HEAD { deny all; }
    if ($arg_type != \"narrative.update\") { return 404; }
    include snippets/proxy-params.conf;
    rewrite ^/\(.slug)(/api/.*)$ $1 break;
    proxy_pass http://127.0.0.1:\(.listener.port);
}"' "$cfg"
} > "$out/listen-sources.conf"
jq -r '[.sources[].slug] | join(" ")' "$cfg" > "$out/slugs"
# What each source will do on this node, for the deploy log.
jq -r --arg mode "$node_mode" '.sources[] | "\(.slug)\t\(.listener.mode // $mode)"' "$cfg" > "$out/modes"
