#!/usr/bin/env bash
# Generates site/_config/mail.php (gitignored) from .email (gitignored), so the
# SMTP credentials live in one place. Keeps an existing form-signing secret.
#   scripts/mail-config.sh [state_dir]
# state_dir: writable directory for the contact form's rate limit (optional).
set -euo pipefail
cd "$(dirname "$0")/.."
[[ -f .email ]] || { echo "no .email; contact form stays unconfigured" >&2; exit 0; }
out=site/_config/mail.php
STATE_DIR="${1:-}" OUT="$out" php -r '
// .email is KEY=VALUE lines (values may contain spaces, optional quotes).
$env = [];
foreach (file(".email", FILE_IGNORE_NEW_LINES) as $line) {
    if (preg_match("/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$/", $line, $m)) {
        $env[$m[1]] = trim($m[2], "\"\x27");
    }
}
$get = fn ($k) => $env[$k] ?? "";
$old = is_file(getenv("OUT")) ? (include getenv("OUT")) : [];
$cfg = [
    "to"        => "contact@vrontier.org",
    "from"      => $get("EMAIL_ADDRESS"),
    "from_name" => $get("EMAIL_NAME") ?: "Listening Observatory",
    "secret"    => (is_array($old) && !empty($old["secret"])) ? $old["secret"] : bin2hex(random_bytes(32)),
    "state_dir" => getenv("STATE_DIR") ?: "",
    "smtp"      => [
        "host"   => $get("SMTP_SERVER"),
        "port"   => (int) $get("SMTP_PORT"),
        "secure" => (int) $get("SMTP_PORT") === 465 ? "ssl" : "tls",
        "user"   => $get("EMAIL_USER"),
        "pass"   => $get("EMAIL_PASSWORD"),
    ],
];
file_put_contents(getenv("OUT"), "<?php\n// Generated by scripts/mail-config.sh from .email; do not edit or commit.\nreturn " . var_export($cfg, true) . ";\n");
'
chmod 600 "$out"
echo "wrote $out"
